messages:
  nonexistent: "<red>That gradient does not exist."
  no-permission: "<red>You do not have permission to do this."
  not-equipped: "<red>You do not have a gradient equipped."
  equip-change: "<green>Your name is now %placeholder%."
  reload: "<green>The plugin has been reloaded."
  no-name: "<red>You must add '%name%' where the player name should go."
  already-exists: "<red>A gradient with that name already exists."

menu:
  menu-title: "        ᴘʟᴀʏᴇʀ ɢʀᴀᴅɪᴇɴᴛꜱ"
  menu-borders: true
  item-name: "%placeholder%"
  item-lore:
    - "<dark_gray>ɢʀᴀᴅɪᴇɴᴛ"
    - ""
    - "<gray>By clicking here you"
    - "<gray>You will equip this"
    - "<gray>gradient."