messages:
  nonexistent: "<#D91C1C>That gradient does not exist."
  no-permission: "<#D91C1C>You do not have permission to do this."
  not-equipped: "<#D91C1C>You do not have a gradient equipped."
  equip-change: "<#82D91C>Your name is now <reset>%placeholder%<#82D91C>."
  reload: "<#82D91C>The plugin has been reloaded."
  no-name: "<#D91C1C>You must add '%name%' where the player name should go."
  already-exists: "<#D91C1C>A gradient with that name already exists."

menu:
  menu-title: "        ᴘʟᴀʏᴇʀ ɢʀᴀᴅɪᴇɴᴛꜱ"
  menu-borders: true
  item-name: "%placeholder%"
  item-lore:
    - "<dark_gray>ɢʀᴀᴅɪᴇɴᴛ"
    - ""
    - "<gray>By clicking here you"
    - "<gray>You will equip this"
    - "<gray>gradient."